name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo "$GITHUB_SHA_SHORT = ${{ env.GITHUB_SHA_SHORT }}"

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: tests
    environment: prod
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
        with:
          path: ./app
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get app version
        run: |
          cd ./app
          echo "$PWD"
          echo "-----------------------"
          ls -a
          echo "IMAGE_NAME=$(npm run name --silent)" >> $GITHUB_ENV
          echo "VERSION=v$(npm run version --silent)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Checkout Application Config
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-config
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ./app-config
      - name: Read deployment file
        run: |
          cd ./app-config
          git config user.email github-action@gmail.com
          git config user.name github-action
          sed -i 's+${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}.*+${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}+g' ./prod/deployment.yml
          git add .
          git commit -m 'Done by GitHub Actions: ${{ env.VERSION }}'
          git push
    outputs:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      VERSION: ${{ env.VERSION }}

  git:
    name: Update Git Repo
    needs: build
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout Application Config
#        uses: actions/checkout@v3
#        with:
#          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-config
#          ssh-key: ${{ secrets.SSH_KEY }}
#          path: ./app-config
      - name: Read Test ENV
        run: |
          echo "$PWD"
          echo "${{ steps.build.outputs }}"
          echo "${{ steps.build.outputs.VERSION }}"
          echo "${{ steps.build.outputs.IMAGE_NAME }}"
          echo "-----------------------"
          ls -a
