name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get app version
        run: |
          echo "IMAGE_NAME=$(npm run name --silent)" >> $GITHUB_ENV
          echo "VERSION=v$(npm run version --silent)" >> $GITHUB_ENV
    outputs:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      VERSION: ${{ env.VERSION }}


  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: tests
    environment: prod
    steps:
      - name: Get Env
        run: |
          echo "IMAGE_NAME=${{ needs.tests.outputs.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "VERSION=${{ needs.tests.outputs.VERSION }}" >> $GITHUB_ENV

      - name: Checkout Application
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  git:
    name: Update Git Repo
    needs: [tests, build]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Get Env
        run: |
          echo "IMAGE_NAME=${{ needs.tests.outputs.IMAGE_NAME }}" >> $GITHUB_ENV
          echo "VERSION=${{ needs.tests.outputs.VERSION }}" >> $GITHUB_ENV

      - name: Checkout Application Config
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-config
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Read deployment file
        run: |
          git config user.email github-action@gmail.com
          git config user.name github-action
          sed -i 's+${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}.*+${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}+g' ./prod/deployment.yml
          git add .
          git commit -m 'Done by GitHub Actions: ${{ env.VERSION }}'
          git push
