name: Docker Image CI
on:
  push:
    branches: [ "master" ]
#  workflow_call:
#    secrets:
#      DOCKERHUB_HOST:
#        required: true
jobs:

  tests:
    runs-on: ubuntu-latest
    environment: prod
    env:
      DOCKERHUB_HOST: ${{ secrets.DOCKERHUB_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Tests1
        run: echo "Tests- ${{ secrets.DOCKERHUB_HOST }}"
      - name: Tests2
        run: echo "$DOCKERHUB_HOST + $DOCKERHUB_USERNAME + $DOCKERHUB_PASSWORD"

  build:
    runs-on: ubuntu-latest
    needs: tests
    environment: prod
    env:
      IMAGE_NAME: "sulikoks/k8s-demo:test"
    steps:
    - uses: actions/checkout@v3
    - name: Login in Docker HUB
      run: echo "${{ secrets.DOCKERHUB_HOST }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin "${{ secrets.DOCKERHUB_PASSWORD }}"
    - name: Build the Docker image
      run: docker build -t "$IMAGE_NAME" .
    - name: Push the Docker image
      run: docker push "$IMAGE_NAME"
