name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    environment: 'DOCKERHUB_HOST'
    steps:
      - name: Tests
        run: echo "here must be tests"
      - name: Tests
        run: echo "$DOCKERHUB_HOST"

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#    - name: Push the Docker image
#      run:
