name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo "$GITHUB_SHA_SHORT = ${{ env.GITHUB_SHA_SHORT }}"

  build:
    runs-on: ubuntu-latest
    needs: tests
    environment: prod
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
        with:
          path: ./app
      - name: Go to app directory
        run: |
          echo "$PWD"
          ls -a
          cd ./app
          echo "$PWD"
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get app version
        run: |
          echo "$PWD"
          ls -a
          echo "IMAGE_NAME=$(npm run name --silent)" >> $GITHUB_ENV
          echo "VERSION=v$(npm run version --silent)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Checkout Application Config
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-config
          ssh-key: ${{ secrets.SSH_KEY }}
          path: ../app-config
      - name: Read deployment file
        run: |
          cd ../app-config
          cat ./prod/deployment.yml
